### ISSUE TITLE
Create separate data package (hySpc.chondro) for chondro 

### ISSUE THREAD

**Issue by eoduniyi** [r-hyperspec/hySpc.chondro#1]
I'm on my way to properly create **hySpc.chondro** package. 

- [x] Create repo  `r-hyperspec/hySpc.chondro`.
- [x] Copy **chondro* related functions from `cbeleites/hyperSpec` to  `r-hyperspec/hySpc.chondro`.
- [x] Review and update the documentation.
- [x] Add unit tests:
    + Several simple tests were added.
- [x] Update vignette:
    + The vignette was minimally updated. A more comprehensive update could be performed after the package is created.
- [x] Fix issues to make `r-hyperspec/hySpc.chondro` to pass R-CMD-check.
- [x] Create **pkgdown** website:
    + (Find it here: https://r-hyperspec.github.io/hySpc.chondro/).
- [x] Update the main webpage (https://r-hyperspec.github.io/) with the link to this repo.
- [x] Copy the **newest** labels (tags) from repo `cbeleites/hyperSpec`:
- [x] License the package correctly:
- [x] Assign the authors and contributors correctly
- [x] Properly deprecate appropriate functions in `cbeleites/hyperSpec`:
    + See  cbeleites/hyperSpec#244

**Comment by GegznaV** [comment]
About the **pkgdown** website, it is already created:

![image](https://user-images.githubusercontent.com/12725868/89151933-b3528200-d56a-11ea-841f-6ba88886708d.png)

So, @eoduniyi, please:

1) Enable Git Pages for `gh-pages` branch,
2) Add URL in the description of this repo. THe URL should be https://r-hyperspec.github.io/hySpc.chondro/ (similarly to https://github.com/cbeleites/hyperSpec/issues/158)

**Comment by eoduniyi** [comment]
Done!

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/89152601-24df0000-d56c-11ea-9e55-f6bb0422e1bc.png)

I did that last week while reviewing other `r-hyperspec` repos. Please, check the website.

***


@eoduniyi, please, grant me (and all `@r-hyperspec/r-hyperspec` team) write access to this repo.

**Comment by GegznaV** [comment]
This part works, thanks 👍 

![image](https://user-images.githubusercontent.com/12725868/89152874-83a47980-d56c-11ea-8e02-16d095def8ae.png)

**Comment by eoduniyi** [comment]
> ![image](https://user-images.githubusercontent.com/12725868/89152601-24df0000-d56c-11ea-9e55-f6bb0422e1bc.png)
> 
> I did that last week while reviewing other `r-hyperspec` repos. Please, check the website.
> 
> @eoduniyi, please, grant me (and all `@r-hyperspec/r-hyperspec` team) write access to this repo.

Will try my best!

**Comment by eoduniyi** [comment]
> > ![image](https://user-images.githubusercontent.com/12725868/89152601-24df0000-d56c-11ea-9e55-f6bb0422e1bc.png)
> > I did that last week while reviewing other `r-hyperspec` repos. Please, check the website.
> > @eoduniyi, please, grant me (and all `@r-hyperspec/r-hyperspec` team) write access to this repo.
> 
> Will try my best!

@GegznaV do you have write access now?

**Comment by GegznaV** [comment]
> @GegznaV do you have write access now?

Yes, I have. Thank you, @eoduniyi

**Comment by eoduniyi** [comment]
> > > ![image](https://user-images.githubusercontent.com/12725868/89152601-24df0000-d56c-11ea-9e55-f6bb0422e1bc.png)
> > > I did that last week while reviewing other `r-hyperspec` repos. Please, check the website.
> > > @eoduniyi, please, grant me (and all `@r-hyperspec/r-hyperspec` team) write access to this repo.
> > 
> > Will try my best!
> 
> @GegznaV do you have write access now?

Yessssss

**Comment by GegznaV** [comment]
> Properly deprecate appropriate functions in `cbeleites/hyperSpec`:

@eoduniyi, I will do this, OK

**Comment by GegznaV** [comment]
I think the package is created. Now we can polish it.
