### ISSUE TITLE
Error with pandoc-citeproc

### ISSUE THREAD

**Issue by eoduniyi** [r-hyperspec/hySpc.chondro#13]
@GegznaV I'm getting the following error anytime I try to build or document:

```
E> Error running filter pandoc-citeproc:
E> Could not find executable pandoc-citeproc
E> Error: processing vignette 'chondro.Rmd' failed with diagnostics:
E> pandoc document conversion failed with error 83
E> --- failed re-building ‘chondro.Rmd’
```

**Comment by GegznaV** [comment]
Did you run it several times or just once?

**Comment by GegznaV** [comment]
Did you run it locally or on CI?

**Comment by GegznaV** [comment]
P.S. In this situation, instead of `question` and `bug` labels, use `possibly bug`.

**Comment by GegznaV** [comment]
I cannot reproduce the issue on my PC. So it is definitely not a bug in **hySpc.chondro**.

@eoduniyi Do you have the newest version of RStudio?

**Comment by eoduniyi** [comment]
Installing the latest version of R Studio 1.3 generates this still:
```
Updating hySpc.chondro documentation
Warning: Version of roxygen2 last used with this package is 7.1.1.  You only have version 7.1.0
Loading hySpc.chondro
Updating vignettes
Rebuilding chondro.Rmd
Error running filter pandoc-citeproc:
Could not find executable pandoc-citeproc
Error: pandoc document conversion failed with error 83
Execution halted
```

**Comment by GegznaV** [comment]
First, you should restart computer after installation.

Second, you should update R packages:

> Warning: Version of roxygen2 last used with this package is 7.1.1.  You only have version 7.1.0

Third, if it persists after these steps, the problem is here:

> Could not find executable pandoc-citeproc

You should Google how to solve it. Have you set some custom environment variables for Pandoc?

**Comment by GegznaV** [comment]
Is this solved?

**Comment by eoduniyi** [comment]
Yes, this problem got solved when I linked RStudio to the correct instance of `pandoc-citeproc` and you suggested. Going to close this issue now.
