### ISSUE TITLE
Import read.txt.Renishaw() from a correct package

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.chondro#9]
Function `read.txt.Renishaw()` will be moved from **hyperSpec** soon. So additional dependency should be added to make this code work.

https://github.com/r-hyperspec/hySpc.chondro/blob/1864633eb26a0f5c364b5b7297dc675741c67a30/data-raw/chondro.R#L11

**Comment by cbeleites** [comment]
Since this is in `data-raw/` and in the vignette only, wouldn't a Suggest be sufficient?

**Comment by bryanhanson** [comment]
@cbeleites can you give me admin privledges on `hyperSpec`? I need to set up a secret token for this task.

**Comment by GegznaV** [comment]
> 
> 
> Since this is in `data-raw/` and in the vignette only, wouldn't a Suggest be sufficient?

By 'dependency' I meant any of `Suggests`, `Imports`, `Depends`. And yes, `Suggests` should be sufficient. But currently, the name of the package is unknown.

**Comment by cbeleites** [comment]
The correct function is `hySpc.read.txt::read_txt_Renishaw()`
